// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsRU-Hy-tbF6Rw6cpET2NcJVWhXzVbEZE',
    appId: '1:494398397032:web:e09e77371ea0cae96439dd',
    messagingSenderId: '494398397032',
    projectId: 'controle-financeiro-54888',
    authDomain: 'controle-financeiro-54888.firebaseapp.com',
    storageBucket: 'controle-financeiro-54888.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEyYK69oXZh_A5HHbS0LJdusypj1rdTts',
    appId: '1:494398397032:android:1cda212084e7c9456439dd',
    messagingSenderId: '494398397032',
    projectId: 'controle-financeiro-54888',
    storageBucket: 'controle-financeiro-54888.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk4V6EIaFKpV0hfI1ZmPlPQ-VD8ZcEfw4',
    appId: '1:494398397032:ios:7561ecbef914618b6439dd',
    messagingSenderId: '494398397032',
    projectId: 'controle-financeiro-54888',
    storageBucket: 'controle-financeiro-54888.firebasestorage.app',
    iosBundleId: 'com.example.controleFinanceiro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsRU-Hy-tbF6Rw6cpET2NcJVWhXzVbEZE',
    appId: '1:494398397032:web:2a18c1dc5f5645766439dd',
    messagingSenderId: '494398397032',
    projectId: 'controle-financeiro-54888',
    authDomain: 'controle-financeiro-54888.firebaseapp.com',
    storageBucket: 'controle-financeiro-54888.firebasestorage.app',
  );
}
